/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'HimnarioID';
  static const String PLUGIN_VERSION = '4.0.1+27';
  static const String ADULTOS4 = 'assets/adultos4.pdf';
}
