// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCqCbyJOW-OJXP1qZPO8T69NwbXVSe4Oo',
    appId: '1:378820595756:web:ee26fc89693ebf991c4189',
    messagingSenderId: '378820595756',
    projectId: 'appid-78919',
    authDomain: 'appid-78919.firebaseapp.com',
    storageBucket: 'appid-78919.appspot.com',
    measurementId: 'G-NXG72PN09P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaVfhCM877lDGdaXVHsg4DP0xKFbET21I',
    appId: '1:378820595756:android:1876b8be1fc7edd21c4189',
    messagingSenderId: '378820595756',
    projectId: 'appid-78919',
    storageBucket: 'appid-78919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_SmcBInOnlH-8sci9ul87XHLxAB7mlY',
    appId: '1:378820595756:ios:4ffd118b963cfe9d1c4189',
    messagingSenderId: '378820595756',
    projectId: 'appid-78919',
    storageBucket: 'appid-78919.appspot.com',
    iosBundleId: 'com.jimmy.appId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs_SmcBInOnlH-8sci9ul87XHLxAB7mlY',
    appId: '1:378820595756:ios:4ffd118b963cfe9d1c4189',
    messagingSenderId: '378820595756',
    projectId: 'appid-78919',
    storageBucket: 'appid-78919.appspot.com',
    iosBundleId: 'com.jimmy.appId',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCqCbyJOW-OJXP1qZPO8T69NwbXVSe4Oo',
    appId: '1:378820595756:web:b8a5e4ec1d2feb781c4189',
    messagingSenderId: '378820595756',
    projectId: 'appid-78919',
    authDomain: 'appid-78919.firebaseapp.com',
    storageBucket: 'appid-78919.appspot.com',
    measurementId: 'G-82E094VN6W',
  );
}
